### ISSUE TITLE
Add a build instruction to the Wiki or to the README file

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#1]
Currently the repository contains no instructions on how to build Rails locally. 
Because this is an essential information needed to develop on Rails such an instruction should be added either to the Wiki or to the README file.
If it is added to the Wiki I would suggest to add a link to the instruction page to the README.

**Comment by neutronc** [comment]
I am currently trying to do that, can you check if you can edit the Wiki ?

**Comment by madoar** [comment]
I think I don't have the rights to edit the Wiki, at least I see no "Edit" or "New Page" buttons.

**Comment by neutronc** [comment]
You should have now. Since i currently dont know how to seperate that from write access to the repository you also have that so please take the necessary caution.
