### ISSUE TITLE
Need a persistance on game related objects that get randomized (Privates,Public, Minor Companies)

### ISSUE THREAD

**Issue by neutronc** [Rails-18xx/Rails#108]
A number of variants have certain randomisation features lately.
With the current save and load logic its not possible to create those games.
A persistance is needed to keep the configuration of Games with randomisations replayable.
Variants in my mind:
1822-Family
18Ireland
1857 (Iberia)
18Chesapeake
and probably others...
Action mechanismn is still needed for playbility. Most randomisations sofar are determined once at game start.

**Comment by madoar** [comment]
What do you mean by `randomisations`?

**Comment by neutronc** [comment]
1822 is randomising the appearance of privates, minors and majors
18Chesapeake is randomising the appearance of the secondary paper for the last private
18Ireland is randomising the order of appearance of the major company, and randomising three privates slot 2,3,4 on the startpacket.

**Comment by madoar** [comment]
Can't we add a `seed` to the game state? This seed should be generated during the game creation. Afterwards it can be used to generate random values in a deterministic manner?

**Comment by neutronc** [comment]
Look at Pull Request #111
