### ISSUE TITLE
unable to dump presidency in 1835

### ISSUE THREAD

**Issue by bearerer** [Rails-18xx/Rails#129]
In the attached savegame user Frank should be able to sell either 10% or 20% of HE.

Apparently this bug exists since issue #77 .

[1835_20200328_1639_Frank.zip](https://github.com/Rails-18xx/Rails/files/4452857/1835_20200328_1639_Frank.zip)

**Comment by neutronc** [comment]
What version of Rails are you using ? Can you supply a save game please ?

**Comment by neutronc** [comment]
the most recent one is 2.1 can be found here or on Sourceforge
https://github.com/Rails-18xx/Rails/releases/tag/v2.1beta1

But still the fix i had prepared for a different scenario doesnt work in your game interesting. Going to check that.

**Comment by bearerer** [comment]
We started the game with a build from January 2020 (branch rails_2_develop) Hence the savegame tag I guess.

There we ran into this bug: #130. 
-> Falsely rearranging the shares during a president change.

We saw a potential fix -> #77 and updated the game. Now player Frank wasn't able to sell his HE shares anymore at all.

**Comment by neutronc** [comment]
Fixed with PR #204

**Comment by bearerer** [comment]
Works like a charm 🚂🚃🚃

**Comment by neutronc** [comment]
glad to hear
