### ISSUE TITLE
certificate exchange in 1835: how can we help?

### ISSUE THREAD

**Issue by bearerer** [Rails-18xx/Rails#130]
> 1835 bugs
After president change there is no way to select the certificates to exchange (this is done by the previous director), partial fix is implemented: prefer 10% to 5%

This bug is currently breaking our games. Will there be a fix in the near future? Can we help? (Two developers with a bit of time at hand since Corona keeps us at home anyway).

**Comment by neutronc** [comment]
any help is appreciated if you know your way around in Java :)
But to reconstruct the bug i need a save game

**Comment by neutronc** [comment]
i can give you an introduction in the code base via discord/twitch if you are interested, just lets organise a time and day.
OTherwise fork the repo here at Github, The code you are looking for is in src.main.java.net.sf.rails.game.Stockround.java and
src.main.java.net.sf.rails.game.specific._1835.Stockround_1835.java
Functions

**Comment by kepakiano** [comment]
Hey, I'll chime in on this. I'm the second dev @bearerer mentioned. I just created this savegame using the current rails_2_develop branch. Peter has 2x10% BA, Hans has 2x10% and the President's share. Jan has 2x10% and 1x 20%. It's Hans' turn. If he dumps the presidency by selling 10% BA, the presidency goes to Jan. Jan has 2x10% and 1x20%. Hans should be able to choose which one of the two packages he gets to make up for his 20% ("Der alte Direktor bestimmt die Stückelung"). However, he is given 2x10%.
[Hans_sells_BA.zip](https://github.com/Rails-18xx/Rails/files/4460858/Hans_sells_BA.zip)

**Comment by neutronc** [comment]
Just give me a sutiable time slot (i am on CEST) and in home office work :)

**Comment by neutronc** [comment]
And yes i know about the Problem with the replacement shares, that simply hasnt been implemented.

We can discuss this during the code Intro if you guys would like.

**Comment by neutronc** [comment]
i'll add you guys to the team and grant you access to the repository.

**Comment by kepakiano** [comment]
Would tomorrow work for you? I'd be available all day.

**Comment by neutronc** [comment]
Ok lets schedule a meeting then tomorrow 5pm CEST ?
And btw we have a slack channel, i'll post the invite link here again.

**Comment by neutronc** [comment]
https://join.slack.com/t/rails-18xx/shared_invite/zt-dcq83imv-uFnJ8h5LqyOLmZ66eRFTXw

**Comment by bearerer** [comment]
Sounds good. How do we meet up?

**Comment by kepakiano** [comment]
I'll be on Slack tomorrow 5pm CEST :)

**Comment by neutronc** [comment]
Adopted into PR#204
