### ISSUE TITLE
Merge 2.1 game play fixes into 2.2

### ISSUE THREAD

**Issue by neutronc** [Rails-18xx/Rails#158]
The fixes in 2.1 for 1835 (several issues) and 1856 Bridge rights should be merge to this code base after the release of 2.1

**Comment by blentz** [comment]
So, being that I recently archived the old branches, I'm happy to take on the task of bringing any code over from the archive.

Let me know which branch I should target, and I can help bring that code over.

Also, open question: Do you want just the code or do you also want the commit history? Doing a simple diff & patch is very quick and easy. Moving the commits between repos is possible, but a little more involved.
