### ISSUE TITLE
1830: When force selling shares, presidency is not transferred

### ISSUE THREAD

**Issue by kepakiano** [Rails-18xx/Rails#185]
In this savegame, the player Matze in his role as president of the Erie is forced to sell shares to buy a train. He is the president of the C&O with 40% share value and tied with Pierre. If he sells 20% C&O, the presidency should be transferred immediately to Pierre (at least according to my German rulebook from the Lookout reprint: "Führt der Verkauf von Aktien dazu, dass sich der Direktor einer anderen Gesellschaft ändert, passiert das sofort"), but isn't. Instead, Matze remains president with just 20% of shares.
[1830_20200426_0708_Matze2.zip](https://github.com/Rails-18xx/Rails/files/4534798/1830_20200426_0708_Matze2.zip)

**Comment by neutronc** [comment]
you will have to adapt the ShareSellingRound Class the same way you did adapt the StockRound Class

**Comment by neutronc** [comment]
Fix with PR#204
