### ISSUE TITLE
Problem with log4j configuration

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#22]
One of the responsibilities of the class `ConfigManager` is the initialization of the logging framework for rails.
To achieve this the class sets two static fields:
```java
    // Log4j command line option, compare log4j documentation
    private static final String LOG4J_CLI_OPTION = "log4j.configuration";
    // Default Log4j configuration-file
    private static final String LOG4J_CONFIG_FILE = "log4j.properties";
```

Afterwards the logging framework will be initialized via:
```java
    private static void startlog4j() {
        
        // log4j settings
        String log4jSelection = System.getProperty(LOG4J_CLI_OPTION); 
        if (!Util.hasValue(log4jSelection)) {
            log4jSelection = LOG4J_CONFIG_FILE;
        }
        // Sets those settings
        System.setProperty("log4j.configuration", log4jSelection);
        System.out.println("log4j.configuration =  " + log4jSelection);
   
        // Activate logger
        log = LoggerFactory.getLogger(ConfigManager.class);
        log.debug("Activate log4j logging using configuration file = " + log4jSelection);
        
    }
```

The problem with this code is, that the codebase doesn't seem to contain either a `log4j.properties` nor a `log4j.configuration` file.

I think this is the reason, for not receiving any debug output during the tests in #18.

**Comment by neutronc** [comment]
From the 1.9 branch.

[log4j.properties.zip](https://github.com/Rails-18xx/Rails/files/1149328/log4j.properties.zip)
[my.properties.zip](https://github.com/Rails-18xx/Rails/files/1149329/my.properties.zip)

**Comment by madoar** [comment]
I just discovered, that we don't have a dependency to `log4j` anymore, but instead to `logback`.
So I think we should change the `ConfigManager` class to work with `logback` correctly
