### ISSUE TITLE
18AL does not show the correct number of remaining tiles

### ISSUE THREAD

**Issue by slapphappyjazz** [Rails-18xx/Rails#220]
When playing 18AL, we noticed that the numbers of remaining tiles weren't being updated in the Info>Remaining Tiles information.  However, on the map itself, when a hex was selected and the list of legal tiles was shown on the left, the numbers were correct.
When I load a saved game, the numbers on the Remaining Tiles information is correct, but when I play on, the numbers aren't updated.  For example. load this game, check the number of #57 tiles listed, then play the move for the first company (laying a straight city) and check the number again.  The number doesn't change.
This is odd, becase it worked for 1830 yesterday, and I'd expect the code to be generic across different titles.

[18AL_20200503_1319_OperatingRound 4.1.rails.zip](https://github.com/Rails-18xx/Rails/files/4640597/18AL_20200503_1319_OperatingRound.4.1.rails.zip)

**Comment by jklap** [comment]
My recollection is the quick fix added for this was to update the #s when the window was activated-- but if you have it open in the background and are referencing it without bringing it forward, then yes I don't think they would update. This quick fix was to deal with the fact the numbers never updated but a real fix would require the window being notified when the laid tiles changed to handle all possible variant tile lay scenarios. If you have a chance if you can verify this is the behavior...

**Comment by slapphappyjazz** [comment]
If I open the window, close it again, lay the tile, and re-open the window, the number is not updated.
However, if I don't open the window before laying the tile, then open the window, the number is updated.
So it looks like just opening the window once may be preventing the number from being updated, even if the window is closed again.
We opened the window early in the game in order to view the special tiles, so I would hazard a guess that the numbers were never updated from that time on.  That would explain why we saw this behaviour in 18AL but not in 1830, because we were familiar with the tile set in 1830 and didn't view the remaining tiles information until late in the game.

**Comment by jklap** [comment]
Ah-- so it looks like I did fix up my original hack to refresh the counts when the window was activated to be driven based on tiles laid via the `TileManager`. I'm guessing that some of these tiles are being handled outside of that logic-- let me take a look.

**Comment by jklap** [comment]
Confirmed that this is working fine with the current dev build, the remaining tiles #s are updated correctly if the window is open; opened after the tile is laid; opened, closed and then reopened; updated if an undo is actioned.
