### ISSUE TITLE
1880 saved game doesn't load properly

### ISSUE THREAD

**Issue by slapphappyjazz** [Rails-18xx/Rails#224]
It says "load interrupted; you can play the game from here".  This is using Rails2.1beta1.
[1880_20200425_1250_OperatingRound 2.1.rails.zip](https://github.com/Rails-18xx/Rails/files/4640801/1880_20200425_1250_OperatingRound.2.1.rails.zip)

**Comment by neutronc** [comment]
Hi Dave,
sorry for coming back that late. What did the player originally do ?
I found a different bug regarding to the graphics in 2.1.

Was he using the RocketPower to buy the 2 or did he buy the 2 the normal way ?

**Comment by neutronc** [comment]
Hi Dave, apparently the JHU didnt buy a train, theres no BuyTrain Action in the Save game for that. So on Replay the game engine declares the following actions invalid. What did the player do ?
By accident clicked on Done and nobody caught the error ? Or used the specialPower and that didnt get registered ?

Please explain :)

**Comment by slapphappyjazz** [comment]
Hi Martin, 
I've reproduced this bug by playing the game from an earlier save.  If you load the attached file, it should load OK into the JHU's move.  If I thenuse the special train purchase option for the Rocket of China, then run the train, and save the game, the saved game doesn't load properly.

I also noticed that if you can click on the special train purchase option multiple times and it buys you a train each time!  

I don't know whether the same problem occurs if you use the Rocket of China during the usual train purchase phase via the "buy train" option.  This was using the Special menu earlier in the company's turn.
Dave.
[1880_20200606_1602_OperatingRound 1.1.rails.zip](https://github.com/Rails-18xx/Rails/files/4740594/1880_20200606_1602_OperatingRound.1.1.rails.zip)

**Comment by neutronc** [comment]
Thanks Dave,

i had feared so since 1880 is the first game having a private with a train buy card. And i Think i used the buy Train Action.... That of course comes after the Train Run Phase..
Now how the f to clean that and why are you the first one to stumble on that problem..
Must have something to do with the move to 2.0+ Code base..
I'll look into that.
Thanks again for the effort.
Regards
Martin

**Comment by neutronc** [comment]
IN 2.2-Beta 2 this doesnt happen anymore.
