### ISSUE TITLE
18Scan problems due to routing errors.

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#229]
1. On laying the yellow Copenhagen tile (F3, #403), pointing to Kiel, a NullPointerException occurs at NetworkVertex line 242. Saved file attached:
[18Scan_CopenhagenTileCrash.zip](https://github.com/Rails-18xx/Rails/files/4653025/18Scan_CopenhagenTileCrash.zip)
Now #403 is an unusual tile with a City only connected to a town, and that town connected to one edge. Perhaps the code does not expect this?

2. In the example below, the blue route for a 2+2 train should have extended to Kiruna (A20) but stops in A18. The pink route is for a 2-train. Saved file:
[18Scan_WrongSNJrunToKiruna.zip](https://github.com/Rails-18xx/Rails/files/4653030/18Scan_WrongSNJrunToKiruna.zip)
![18ScanKirunaBug](https://user-images.githubusercontent.com/13908049/82376958-3449b500-9a23-11ea-8956-99c051df76ba.jpg)
(Kiruna should be a run-through town (worth 50 in this stage), but probably the tile def is incorrect in that sense. But that should not affect correct routing as indicated above).

**Comment by erik-vos** [comment]
This is tile #403: 
![18ScanCopenHagenBug](https://user-images.githubusercontent.com/13908049/82377556-1fb9ec80-9a24-11ea-958a-c0766c8d7dbc.jpg)

**Comment by jklap** [comment]
Rails looks to be running the pink route with the 2+2 train -- need to dig in further, off the cuff it looks like it's not the (exact) same issue as #221

**Comment by erik-vos** [comment]
I want to split off the Copenhagen issue. This has turned out to be a configuration issue: the preprinted tile at F3 did not include the town that the yellow upgrade (#403) has, and MapHex.upgrade() cannot (yet) handle that. F3 now has a new tile #-3012 that has both a city and a town. The fix will probably be included in a larger set of config fixes for 18Scan.
This problem will return once 1841 (v1) comes in sight, where the map shows Venezia without the town that the yellow upgrade has.

So this issue needs to deal with the routing around Kiruna only.

**Comment by erik-vos** [comment]
This issue will be closed, as it turned out to be a configuration problem. For Kiruna it seems OK now, although I have not yet seen a run-through case.
However, there is another 18Scan routing issue for which I will open a new one.
