### ISSUE TITLE
1856 formation of the cpr 

### ISSUE THREAD

**Issue by Hessbert84** [Rails-18xx/Rails#235]
after the first 6 train the new president of the cpr gets 30% of shares, the rest get nothing. no matter how much the players exchange

**Comment by neutronc** [comment]
Which version of Rails are you using ?
Can you send us a save game ?
That bug got fixed on a newer version if i recall correctly
Regards
Martin

**Comment by Hessbert84** [comment]
Hey Martin,

 

we use rails-2.0.RC3

we lost the last game without a savegame when we tried to jump back in history before the formation oft he cpr. I played a hotseat game just with myself today to recap the bug. 

Savegame: 1856_20200601_1155_Sebastian

 

Player „Christoph“ should have some of the cpr shares but has zero.

I guess, the bug only appears if the cpr shares are worth 10%. I tried it with more compamies merged in, the exchange in 5%-cpr shares seems to work

 

 

Best regards

 

christoph

____________________________

hessbert84@gmail.com <mailto:hessbert84@gmail.com> 

 

 

Von: Dr. Martin Brumm <notifications@github.com> 
Gesendet: Samstag, 30. Mai 2020 23:04
An: Rails-18xx/Rails <Rails@noreply.github.com>
Cc: Hessbert84 <hessbert84@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [Rails-18xx/Rails] 1856 formation of the cpr (#235)

 

Which version of Rails are you using ?
Can you send us a save game ?
That bug got fixed on a newer version if i recall correctly
Regards
Martin

**Comment by neutronc** [comment]
Hi Christoph,
the bug was known and fixed in October 2018. Can you please get the newest version from either sourceforge or here and load your game ? Should be fixed. 
Regards
Martin

**Comment by Hessbert84** [comment]
no problems with 2.1 beta

**Comment by Hessbert84** [comment]
thanks

**Comment by neutronc** [comment]
Thank you, and good luck and if you find other problems please let us know. Every report is appreciated.
Have Fun, and do tell which game you would like to see implemented :)
Regards,
Martin

**Comment by Hessbert84** [comment]
Love to see 1822 and 1849 😊

 

Regards

Christoph 

 

 

Von: Dr. Martin Brumm <notifications@github.com> 
Gesendet: Montag, 1. Juni 2020 16:36
An: Rails-18xx/Rails <Rails@noreply.github.com>
Cc: Hessbert84 <hessbert84@gmail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [Rails-18xx/Rails] 1856 formation of the cpr (#235)

 

Thank you, and good luck and if you find other problems please let us know. Every report is appreciated.
Have Fun, and do tell which game you would like to see implemented :)
Regards,
Martin
