### ISSUE TITLE
Add maven plugin to create .deb installer files

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#24]
It would be quite nice if we add a maven plugin to our project that creates a `.deb` installer for debian systems.
A maven plugin to create `.deb` installers can be found here: https://github.com/tcurdt/jdeb/blob/master/docs/maven.md

**Comment by blentz** [comment]
If we're going to do .debs, we should also do RPMs.

**Comment by neutronc** [comment]
@blentz +1 ;@madoar +1
