### ISSUE TITLE
1880: Shares owned by foreign investors

### ISSUE THREAD

**Issue by slapphappyjazz** [Rails-18xx/Rails#243]
Each foreign investor owns a share of a public company.  This doesn't seem to be shown anywhere in the Status window.
Perhaps the company name could be displayed in "IPO" or "Rights" column for the foreign investor?  
An alternative would be to add a new "FI" column that showed the number of the FI that owns a share for a given company, which would be a cleaner design would take more screen space.

**Comment by neutronc** [comment]
![grafik](https://user-images.githubusercontent.com/6752457/85054807-e9939800-b19c-11ea-959a-da751ab8d76d.png)

**Comment by neutronc** [comment]
is that ok Dave ? @slapphappyjazz

**Comment by slapphappyjazz** [comment]
That looks good.  Thanks.
