### ISSUE TITLE
1880: Map doesn't show rivers

### ISSUE THREAD

**Issue by slapphappyjazz** [Rails-18xx/Rails#244]
One of the privates in 1880 removes the cost of laying track in a river hex.  The Rails map doesn't distinguish river hexes from mountain hexes, so you have to either consult another copy of the map, or remember which terrain values correspond to rivers.  The map should indicate which hexes are rivers.

**Comment by neutronc** [comment]
Removed by introducing 1880 Map as background with the permission of the Authors.
