### ISSUE TITLE
Building a bridge

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#252]
Certain games, such as 1822 and Steam over Holland, have rivers running along hex edges, where it takes a cost to lay the _second_ tile against such an edge (i.e., to complete a bridge). In my first stab at SOH I have marked these edges as "impassable" to make these visible and check the map, but of course this needs be changed. This is not an urgent issue yet, but I would like to bring it into discussion so we might have a solution when the time comes.

An obvious start could be replacing "impassable" by "river", so we get something like
	`<Hex name="J3"  tile="0" river="J5,K2,K4"/>`
but, as I think we will use the existing HexSide class, it might be better to make it more generic (and extendable) by creating a subtag `<Edge>` (or `<Side>`) with a type:
         `<Edge to="J5,K2,K4" type="river" (or "bridge") buildCost="50"/>`
although I think that in practice cost can best be defined in the `<Defaults>` section.
Impassable hexsides should then be marked with
         `<Edge to="D5" type="impassable"/>` 
(the current method could be kept for a while for backwards compatibility).

The "river" type would then be handled as follows:
1. The river is shown on the map in blue, as if it was impassable (perhaps impassability should get a different colour),
2. On laying a tile, a check must be done; perhaps the cost should be added to the LayTile PossibleAction,
3. On route finding and train running, the river edges behave normally and have no financial impact, so the dreaded routing code may remain unaffected.

Comments? Are there any other features related to hex sides that we should include in this concept?

To whet your appetite I am attaching the river-rich SOH map:
![MapWithRivers](https://user-images.githubusercontent.com/13908049/84899066-77418b80-b0a8-11ea-9716-f3cd994556ef.jpg)

(P.S. does anyone know how to turn this picture into an SVG background map? I also have .bmp, .png and other formats if needed. The online services I have tried return an unusable black-and-white composition, and my proficiency with Inkscape has faded).

**Comment by neutronc** [comment]
I do like this concept :) is there a chance to enlarge this with Tunnel targets ? or Bridge Targets that are different hexes ?
e.g. Edge to=J5 type=Tunnel target=K4 as an additional build option ?
1844/1854 have tunnels that surpass a hex ? But if you tunnel theres no normal edge exit possible ?

**Comment by erik-vos** [comment]
Tunnel entrances are needed in 1844, because only specific edges may be used for tunneling. 1854 does not have dedicated tunnel entrances, so I don't see a need to specify these. In both games, the allowance to lay tunnels will be a hex property, so we need new hex types for tunnels only (1844) and tunnels also allowing normal track (1854). And some game-specific overriding methods to handle that. I don't see any impact from tunnels on neighbouring hexes. Please tell me if I'm wrong.
