### ISSUE TITLE
Wrong price when force selling 10% Prussian share

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#255]
When `Bjoern` buys a new `6+` train in the attached game save he is missing 224 money and therefore needs to sell shares to pay the full price. In theory it should be enough to sell a `10%` P share for 212 money and a `10%` WT share for 64 money. After selling the `10%` P share the client only subtracts 106 money from the remaining amount instead of the full 212.

Game save: [1835_20200604_1940_Bjoern.rails.zip](https://github.com/Rails-18xx/Rails/files/4807617/1835_20200604_1940_Bjoern.rails.zip)

**Comment by neutronc** [comment]
Good morning, which version ?

**Comment by madoar** [comment]
It occurs in all 2.2.x versions as far as I know.
