### ISSUE TITLE
1880 - Load Game fails after Rocket was used

### ISSUE THREAD

**Issue by ChrFarwig** [Rails-18xx/Rails#270]
Since 2.1, saved games for 1880 cannot be loaded anymore once the special feature „Rocket of China“ was used. The load gets stuck at 45%.

With 2.0rc1, this issue does not occur

**Comment by neutronc** [comment]
Hi Chris this Issue occurs if someone is actually accidentally using the Rocket Power twice. 
Do you have the game log and a save game available i then can fix the behaviour for you.

**Comment by ChrFarwig** [comment]
Hi,

thanks for responding so fast. Here is the save game that wont load, 
Rocket has only been used once, the log is attached.

Regards,

Christian


Am 26.07.20 um 12:11 schrieb Dr. Martin Brumm:

**Comment by neutronc** [comment]
Hi Christian,
i see the log thanks for that. Question why did you use the cash correction mode ?

But theres no save game attached ?

Regtards,
Martin

**Comment by neutronc** [comment]
You have to upload the save game, Email will not suffice sorry.

**Comment by ChrFarwig** [comment]
Hi,

a save game should have been attached, I try again.

We used cash correction since 2.0 has an issue with private closing if 
the path is blocked by a token (should close but wont), so we do the 
cash transfer to correct the score.

2.2 does not have this issue anymore.

Regards,

Christian

Am 26.07.20 um 13:42 schrieb Dr. Martin Brumm:

**Comment by ChrFarwig** [comment]
Save game attached


[1880_20200725_2349_Wolfhart.rails.zip](https://github.com/Rails-18xx/Rails/files/4977562/1880_20200725_2349_Wolfhart.rails.zip)
