### ISSUE TITLE
1889 - "null" included in company description strings

### ISSUE THREAD

**Issue by o0dano0o** [Rails-18xx/Rails#28]
Hi,

In the map window for 1889 if you click on Info->Companies and then go through each of the public and privates, some of the strings have "null" at the end. It looks like all companies are affected in some way by this.

For example, in private company A, the last line says:
Blocking: K4null

Thanks!

**Comment by neutronc** [comment]
Confirmed as not only tagging 1889. Also 1830 and probably others have that problem.

**Comment by neutronc** [comment]
Fixed by PR #29
