### ISSUE TITLE
18Scan auction isn't implemented properly

### ISSUE THREAD

**Issue by philcampeau** [Rails-18xx/Rails#290]
Currently in the September 15, 2020 build of the app (2.2.1-1 according to my package manager), the auction fuctions like a standard 1830 waterfall auction. According to the rules, players are to take turns bidding for the right to purchase any available private company at face value plus the amount of their bid.

Once a winner is declared and the winner has chosen their private, the next auction is started by the first player to have passed in the previous auction.

**Comment by erik-vos** [comment]
Then somehow this build does not contain much of the 18Scan stuff at all. The auction stuff has been PR-ed into the central repository in June or July; it was among the first things I did on 18Scan this summer, and it works fine from the source code. Only the latest updates on 18Scan, correcting the bonus calculations, are currently missing in the central repository (see my new comment to PR #277).

As I'm not involved with building builds, I can't help any further here.

**Comment by neutronc** [comment]
OK,
no 2.2.1 is a maintenance branch for 2.2. Eriks new code is in the master branch.

**Comment by erik-vos** [comment]
Closed.
