### ISSUE TITLE
Stock Charts do not display ledges.

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#297]
Steam over Holland, on which I'm working, has a linear stock market with ledges. These work fine, but regrettably the stock chart does not display any ledges (nor does it in 1870). Ideally, these should be visible, as in the board game.

To show the ledges, I suppose a somewhat thicker black line would do. Unfortunately (for me), the stock chart has been converted to JavaFX, which is not in my toolbox.

So I hope someone else can pick this up. Use the 1870 initial prototype for testing.

**Comment by neutronc** [comment]
![grafik](https://user-images.githubusercontent.com/6752457/100721976-581d8880-33c0-11eb-8a96-25a459367089.png)
