### ISSUE TITLE
Add dependency management tool

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#3]
Currently it seems like the dependencies needed to build Rails are managed manually in `lib` folder.
I think it would be better to use a dependency management tool like maven, gradle or sbt for this.
These tools can handle the downloading of the dependencies, the build process and running the tests for you.
I'm not sure if Rails is currently using a dependency management tool, because the project contains some `gradle.*` files, but I don't know if they are used and for what they are used.

**Comment by neutronc** [comment]
Stefan set up a basic gradle mechanismn but i am sure that can be improved ! :)

**Comment by madoar** [comment]
I must confess that I have no previous contact with gradle.
I myself have worked with maven quite a lot, so I think this is something someone else should do.

**Comment by madoar** [comment]
#7 finishes the introduction of maven as a dependency management and build system. 
In addition #7 removes all other build system files from the project, to make it clearer for other developers.
