### ISSUE TITLE
Bug 1835 - Prussia share buyable

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#30]
When looking at the appended screenshot you'll discover, that Rails says, Rainer can buy a Prussia (PR) share. The problem is, that he doesn't have enough money to do this, 92 < 154. 
Therefore I would expect rails not to highlight the Prussia share.
![grafik](https://user-images.githubusercontent.com/18488086/28291984-6f1b304e-6b4d-11e7-8f7d-9ab856a8ffdb.png)

**Comment by neutronc** [comment]
You have a savegame available?

**Comment by madoar** [comment]
I have two save games:

- The first save game captures the state directly before buying the first `5` train, which forces everyone else to swap their privates to Prussia shares.
- The second save game contains the end state (Containing the results)

I'll append both, the save game with the later time (21:20) is the end result.
[Rails-bugs.zip](https://github.com/Rails-18xx/Rails/files/1155501/Rails-bugs.zip)
