### ISSUE TITLE
1856 in 2.rc04 Wrong starting check for floated company

### ISSUE THREAD

**Issue by neutronc** [Rails-18xx/Rails#309]
hi all,
another error in 1856 (rails.2.04)
TBG was started in AR 6 but not 60% sold. in AR 7 Player jupp buys 60% of the TGB. next available Train: 8
When in OR 7.1 the TGB want to start, this message came up.

This will never happen, if no one buys 20% TGB. The rules declare, 60% is sufficent.

game-file status: 1 click before starting the TGB.

**Comment by neutronc** [comment]
[1856_20201122_1805_Volker_Kuhnle.zip](https://github.com/Rails-18xx/Rails/files/5595702/1856_20201122_1805_Volker_Kuhnle.zip)

**Comment by erik-vos** [comment]
Fixed.
The being-operational check at the OR turn start did not handle the 8-train case.
Finding the next train number is now centralised in a new method getNextTrainNumberFromIpo() in GameManager_1856. This closes two TODOs about refactoring duplicate code.
