### ISSUE TITLE
Wrong Train  Type used for Bank calculated run in 1856

### ISSUE THREAD

**Issue by neutronc** [Rails-18xx/Rails#310]
we play 1856 in a variant with 8-Trains instead of a Diesel.
After Formation of the CGR the CGR borrows a Train from the Bank.
The revenue was calculated by a Diesel. 460 instead of 360 for an 8-Train.
[1856_20201123_1833_Ulli_Hegemann.zip](https://github.com/Rails-18xx/Rails/files/5595716/1856_20201123_1833_Ulli_Hegemann.zip)

**Comment by erik-vos** [comment]
Fixed (I hope).
As expected (see #309), the 8-train variant was not included in the borrowed train selection.
However, the values I found are different: 450 for the D-train, and 340 for the 8-train. Please let me now if this means that we still have an issue.
