### ISSUE TITLE
1856 Bridges not counted in revenue run

### ISSUE THREAD

**Issue by neutronc** [Rails-18xx/Rails#326]
Hello,
Current game, 1856 with Diesel. WR has an 4-Train, Bridge, the calculation runs the train without the bridge-income. Any solution?
greetings
Volker 

[1856_20201121_1655_Kllaus-J_rgen_Fleischer.zip](https://github.com/Rails-18xx/Rails/files/5775613/1856_20201121_1655_Kllaus-J_rgen_Fleischer.zip)

**Comment by erik-vos** [comment]
Volker,
In the saved file you provided, the WR never had a 4-train or a Bridge token before it closed in OR 6.2 at CGR formation.
Do you have a better file?

**Comment by neutronc** [comment]
Hi Erik,
with 2.2.0 the Private Acquisition of the Company sets the necessary rights on the Public Company (WR) that he is the owner of the Located Bonus. In 2.3.0 this right is not set anymore on the acquiring companies. In 2.2.0 this was still valid. 

Both Private acquiring companies should be getting the right/token upon purchase in 1856.

**Comment by neutronc** [comment]
Hi Erik,
you moved the allocation of the SpecialProperties from PublicCompany to GameManager. That broke the local link to a SpecialProperty for the Company owning that SpecialProperty and thus caused the error if you excercised that. You now somehow need to relink the SpecialProperty back to the owning Company and excercise that for the SpecialBonusToken Right if that is sellable.

**Comment by erik-vos** [comment]
I'll look at that. A test case would help, otherwise I will have to create one. Apparently there is none in the current test set.

**Comment by erik-vos** [comment]
For the record, this is the correct saved file.
[1856_20210105_1905_Klaus-J_rgen_Fleischer.zip](https://github.com/Rails-18xx/Rails/files/5795623/1856_20210105_1905_Klaus-J_rgen_Fleischer.zip)

**Comment by erik-vos** [comment]
Fixed. Will be included in a forthcoming PR.
