### ISSUE TITLE
Bug 1835 - Second "revenue earned" input

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#33]
In the attached screenshot you'll discover a second input field for the revenue earned value (containing 240 in the screenshot).
This field seems to belong to the Hessen company (HE) which was the last company to be played (if I remember correctly).
This input field shouldn't be there.
![grafik](https://user-images.githubusercontent.com/18488086/28292248-81aeeaba-6b4e-11e7-8cab-efb6fdded227.png)

**Comment by neutronc** [comment]
Pease provide a save game thank you. #32 #31 #30 #

**Comment by madoar** [comment]
Please take a look at #30 for the save game.
