### ISSUE TITLE
1830. Emergency Train purchase, presidency not transferred correctly on share sales

### ISSUE THREAD

**Issue by mjshaver** [Rails-18xx/Rails#338]
PRR director is buying a Diesel out of pocket.  He also owns 50% of B&M and another player owns 40%.  The active director sold 30% of the B&M to pay for the Diesel but rails still says he has the presidency of the B&M. (see attached save file)
[1830_20210121_2320_Mike.zip](https://github.com/Rails-18xx/Rails/files/5859563/1830_20210121_2320_Mike.zip)

Rails 2.1Beta1

**Comment by neutronc** [comment]
Hi Mike,
is fixed in the current master branch. 2.3 has this also fixed.
