### ISSUE TITLE
1837 Coal Exchange Round

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#356]
As had already has been mentioned in #346, the Coal Exchange rounds do not work as described in the later v1 and the v2 rules.
Fixing this problem turned out to be harder than I expected.  I am now creating a new issue for it, so its implications can be discussed separate from the maelstrom that issue #346 has become.

The coal exchange round (hereafter: CER) now runs correctly, as far I have been able to test it (not very far). That is: it now runs each time between any pair of "normal" rounds when any coal company merger is possible.  

Points worth noting are:

1. CER numbering: I have decided to number CERs as the _previous_ rounds are, whereby a stock round (SR) number is presumed to have suffix 0. So after SR 2 we can have CER 2.0, and after OR 2.1 comes CER 2.1. This implies that operating rounds must have a suffix > 0. 

2. While testing this, I noticed that operating rounds (ORs) in that version of the code got a one-too-low main number: OR 0.1 in stead of 1.1. This probably was an 1837 artefact, but it caused me to make the round numbering code as a whole a bit more logical. 

3. I also noticed that OR numbering before SR 1 started at 0.0; for consistency I have changed this to 0.1, so a following CER will have the expected number 0.1 as well.

4. The start rounds or initial rounds (IR) were still unnumbered. Following a request in an earlier issue, these now have a simple number, starting at 1.

5. Points 3 and 4 have caused changes in the report files used in regression testing. I had to renew most of the test report files.

Still to do: 

6. The token replacement question is now put to the (former) coal company owner, but should be moved to the major company owner. I plan to combine this question with the one about dropping just acquired trains beyond the current limit.

7. More testing, and using the results to create a few extensive regression test reports.

**Comment by erik-vos** [comment]
I am about to push the current version of the Coal Exchange Round code. I hope I can manage that on Thursday or Friday, so it can be included it in the next release.

The new procedure, which follows the later v1 and the v2 rules, is as follows:

1. After each stock round (SR) and operating round (OR), a coal exchange round (CER) is inserted, as long as any floated major company still has unmerged coal companies.<br>_Question 1: especially after an SR, the start of a CER is rather inconspicious: just the title of the status window changes, and one or two coal company certs get highlighted. Should I add a popup that announces the start of a CER?_
2. The involved major companies are put in current operational order, and for each one steps 3-6 are executed.<br>_Question 2: Should I add a popup to announce each turn of a major company (possibly as an alternative to the CER announcement from Q1)?_
3. a) If the merge is forced, because the company shares are sold out or phase 5 is reached, the mergers are immediately executed, without any user interaction. Step 4 is skipped, and step 5 immediately follows.<br>b) If the merge is optional, each related coal company owner gets a turn to merge it by clicking the highlighted field. If there is more than one owner, their sequence is in normal table order, starting with the major director. 
4. After zero, one or two merger actions, each involved player finishes merging by pressing "Done".
5. If any minor was merged and closed, a popup displays a message reporting the merger(s), and includes checkbox(es) to give the major director the opportunity to select laying a token on each such minor's home hex. The default is no token laying. Pressing "Done" concludes this step.
6. If mergers into this major have left it with too many trains, this must be corrected by discarding one or two of the just acquired trains. This can be done in two ways:
a) if the major excess trains are all of the same type (usually 1G), the discarding is done automatically.
b) otherwise, the major director can indicate which train(s) to discard in a pull-down list.

All executed actions are of course mentioned in the Report Window.

_Question 3: any other messages to display to clarify what is happening?_

Testing has not yet progressed beyond the 3-trains. There are still some cleanups and refactoring to do, but basically it all seems to work. The main thing now is to continue testing to include the National company mergers, and see how that affects the code. In any case, I believe that there is no more need for a separate FinalCoalExchangeRound, as reaching phase 5 is already being checked in the normal CoalExchangeRound.

**Comment by neutronc** [comment]
Hi Erik;

Regarding Q1: yes please
Regarding Q2: Yes additionally to avoid confusion.
Regarding Q3: just the train discard as an info popup ? And maybe a Summary of Actions after the respective CER in the log ?

**Comment by erik-vos** [comment]
Q1 & Q2: done.
Q3: I have added popups for the forced (automatic) actions: closing if sold out, and train discards if only one train type is available.
Let's see how it works out.

I have added some test files, and now need to replace one because of a nasty problem that has kept me busy yesterday, and again it does now. If a major company is related to two coal companies, and both are closed, the token laying step handles both coal companies together in one (new) token laying action. It now turns out, that the sequence of these coal companies in the dialog action varies, and so reloading saved files often leads to invalid action reports. 

The cause appears to be that such info is held in maps of maps (or the new HashMultimaps), so that in the returns from the inner maps the sequence is not fixed. The remedy is to replace these structures with maps of arraylists (or ArrayListMultimaps). 

And so I have to redo again one of the already committed test files...

But I still expect to create the PR today.

**Comment by jdgalt** [comment]
Step 5 seems wrong to me, mostly because it appears to conflate minor companies merging with coal companies merging.

Minor companies merging should follow the same steps as in 1835, except the timing: which phase change causes which trade-ins to be allowed / mandatory is different for each major company.  But I have always played that the token replacement is compulsory for all of them, except for S5 because it is in Italy which is now off-limits.

But assuming this procedure applies only to coal companies, then step 5 goes away, because a coal company has no token except its mine, and major company tokens cannot be played there.

**Comment by erik-vos** [comment]
Yes, step 5 is wrong. I can't remember how that idea has taken hold in my mind, but indeed it is nowhere in the rules. 
I may have misled myself by using the term "minor" also for coal companies in the code, and probably also in some of the displayed texts. 

Removing step 5 looks like an urgent fix to me. @neutronc, can you wait with the release until this is fixed? Should happen tonight or perhaps early tomorrow. I'll look at terminology later on.

**Comment by erik-vos** [comment]
OK, fixed it. Had to finally decide to add a step variable to CoalExchangeRound. Logic is much clearer now. PR follows.
