### ISSUE TITLE
1837: Bosnia and Italy map hex colours

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#361]
Another issue copied from #346.

@hast18xx reports:

more errors 1837:
Bosna Opening in green phase: it is not possible to lay a green tile. Even with map correction only yellow tiles are offered
See SC:
![Bosna opening  in green phase](https://user-images.githubusercontent.com/64490299/110005319-9fe1e200-7d18-11eb-95e1-27c3a31c557e.png)

When I tried to test this, the game even crashed as soon as BH got its first turn. That happened after the first 3+1 train was out. The cause was that the "phase reached" condition for activating Bosnia was set wrongly (probably overseen by me when I reorganised the phase list recently). This has been fixed.

AFAIK once Bosnia opens, the first tiles to be laid should be yellow, so I don't think there really is a problem here. It is unfortunate that the empty hexes look so yellowish: in fact these are blank hexes with just a different hue to mark initial unavailability. I would recommend to give these tiles (-6000...-6007) a more yellow-greenish colour.  After some experimenting, I found "#DCDCB0" pretty satisfactory:

![Bosnia at game start](https://user-images.githubusercontent.com/13908049/111922380-bf5b6780-8a99-11eb-8ea7-3435b85002eb.jpg)
Would that do?

**Comment by jdgalt** [comment]
On the physical map those hexes are yellow but much lighter (paler) yellow than a yellow tile.  This is darker but would do fine.

**Comment by erik-vos** [comment]
I would describe the Bosnia colour on my (old) game more like apple-green, but on this scan it has paled and comes closer to the colour I fiddled yesterday, see above. 
![BosniaMap](https://user-images.githubusercontent.com/13908049/112024464-84f2d880-8b34-11eb-9f74-ef408a925ed1.jpg)

Anyway, I have seen your request for a similar treatment of Italy, which needs the creation of more 'handmade' tiles. I'll come back to that later within this issue, which I'll rename for this purpose.

**Comment by erik-vos** [comment]
What about this colour for Italy?
![1837Italy](https://user-images.githubusercontent.com/13908049/112231736-9375e880-8c37-11eb-920a-553f367a04e1.jpg)

**Comment by jdgalt** [comment]
Looks quite good from here!
