### ISSUE TITLE
Is the Windows 2.4.5 version 64-bit?

### ISSUE THREAD

**Issue by peter-de-boer** [Rails-18xx/Rails#370]
One fellow player cannot run version 2.4.5. He is using Windows 32-bit. The suspicion is that the application only runs on 64-bit. Could that be the case?

**Comment by neutronc** [comment]
Thats something we need to investigate.

**Comment by neutronc** [comment]
Did he try to set and use the compatibility features of Windows 10 ? Or what version is he using ?

**Comment by neutronc** [comment]
After having a quick look in the net:

**Comment by peter-de-boer** [comment]
For a screenshot, see our game here: [https://www.boardgamegeek.com/thread/2625167/hakko-pep-dan-stan-peter-game-4/page/1](url)

**Comment by madoar** [comment]
The installers which are generated in the GitHub Actions should be for x64 systems. The reason is that the common JDKs you can download are for x64 operating systems. This results in 64-bit JREs being included in the installers.

If you manually install a 32bit JRE/JDK on your system (for example from [Adoptopenjdk](https://adoptopenjdk.net/releases.html)) and build Rails on your 32bit system you should be able to execute it on the system as well.
For now we don't append a platform independent jar to the GitHub releases.
Therefore you need to build it yourself currently.

**Comment by neutronc** [comment]
Is it possible to create a platform independant one ? If so we should include that in the build process.

**Comment by madoar** [comment]
It should be possible. The important part is that the jar contains all the native packages for Javafx

**Comment by peter-de-boer** [comment]
Could you pls give a clear instruction how to build Rails? Or alternatively build it for us?

**Comment by peter-de-boer** [comment]
Any feedback to my last question?

**Comment by neutronc** [comment]
Still investigating how to build a jar that can be used by you guys.

**Comment by neutronc** [comment]
try to use the Jar that can be found on the release page. But you will definately need a JDK with a Version of at least 11 installed on your local machine.

**Comment by peter-de-boer** [comment]
> try to use the Jar that can be found on the release page. But you will definately need a JDK with a Version of at least 11 installed on your local machine.
> It starts and runs on my machine..

Where exactly can I find that? On https://sourceforge.net/projects/rails/ I see a dbm, exe, rpm, deb, but no jar...

**Comment by neutronc** [comment]
https://github.com/Rails-18xx/Rails/releases/download/releases%2F2.4.5/rails-2.4.6-alpha-all.jar

**Comment by peter-de-boer** [comment]
Thanks. For some reason I do not see a releases directory when I am on https://github.com/Rails-18xx/Rails, but the file can be accessed. 

My friend tried it, but hit a problem. See his last post on https://www.boardgamegeek.com/thread/2625167/hakko-pep-dan-stan-peter-game-4/page/3.

**Comment by neutronc** [comment]
https://www.azul.com/downloads/zulu-community/?architecture=x86-32-bit&package=jdk-fx&show-old-builds=true

See my answer on your thread :) Sorry thats all i can do in the moment.
