### ISSUE TITLE
18EU: Mandatory train scrapping does not work

### ISSUE THREAD

**Issue by Andy-0711** [Rails-18xx/Rails#381]
In order to find out whether Rails (2.4.5 on Windows 10) could handle the rule, that a player can have >60% of a company until he is able to sell shares (after the company ran at least once [rule 4.3, paragraph 7]) I made a test run and merged 7 (2nd try: 5) minors into a new company.
After that, there are 7 (2nd try: 5) 2-trains in the company so it is required to discard the excess to the train limit (4) at the end of the stock round. The dialog is shown but does not discard any train.

It doesn't matter, whether you cancel the "discard train"-dialog (why can you do that anyway?), click ok or press enter, after selecting the only choice by mouse or keyboard before (or not doing that since it is pre-selected) - nothing happens except the dialog is closed and from now on the game is stuck. If you enable and disable cash or map correction, the dialog reappears - still without any effect.
You can still save the game after that but when you load that savegame it hangs at 92% (after it shows the "discard train"-dialog - sometimes behind the loading window). 

My best guess ist, that either "ok" works like "cancel" or the selection-ID of the combobox is not set or read correctly so nothing happens. (I presume it is by design, that only 1 of the 7 (5) 2-trains is shown in the combobox list.) It also maybe connected to the fact, that these trains are assigned to the minors at game start and therefore can never be bought from the bank,

I have appended an example savegame before all player passing in the stock round.
[18EU_20210330_0932_P1.zip](https://github.com/Rails-18xx/Rails/files/6228515/18EU_20210330_0932_P1.zip)
(I would also have a savegame before merging the 5th minors if needed. I also tried an installation on Windows Server 2016, as well as execution as administrator and got the same result with that savegames. I have only windows-clients to try.)

**Comment by neutronc** [comment]
@Andy-0711 Thank you for reporting this bug. Can you upload the other savegame as well ?

**Comment by Andy-0711** [comment]
Here it is:
[18EU_20210330_0931_P3.zip](https://github.com/Rails-18xx/Rails/files/6228714/18EU_20210330_0931_P3.zip)
(The 0805 is the first try with 7 minors after crashing.)
[18EU_20210330_0805_P1.zip](https://github.com/Rails-18xx/Rails/files/6228713/18EU_20210330_0805_P1.zip)

**Comment by erik-vos** [comment]
In 1837 I have implemented a probably more satisfactory approach. If the company has discardable excess trains of only one type, trains of that type are automatically discarded until the number is below the limit. If there is more than one type, the president gets a choice (still one train at a time), but no cancel option. 

In 1837, having only one discardable type is common, and so it is in your construed 18EU case, where the SNCB happens to have only 2-trains. So in your case autodiscarding will work, but in normal games I expect having only one type will be rare.
Still, generalizing the 1837 approach may be worth to think about.

Are there any games where voluntary train discarding exists (apart from allowed exchanges)? If not, the no-discard option can be dismissed everywhere.

**Comment by neutronc** [comment]
This is caused by a hidden Java exemption in trainCard.discard(). The check actualTrain.value().isObsolete() hits a obsolete filed without a value and thus causes Java to stop exexcuting.
@erik-vos : how was that handled before your changes in May 2020, where was obsolete initialised with false ?

**Comment by neutronc** [comment]
@erik-vos The problem is coming from the point that actualTrain.value() is referring to a null object .. Dont know how that can happen... so its not the isObsolete() check cause thats the subsequent problem. And i do think we have to fix the underlying mechanic cause this might affect more games with merging later on ?

**Comment by erik-vos** [comment]
I had not yet started debugging this, which I will do, but was already thinking forward. Would it be useful to add a flag that sets mandatory or optional discarding, or don't optional discards exist at all?

Being obsolete only applies to games having that feature, I think false is the normal setting.

It's not impossible that earlier changes have introduced a bug, but then it's time to add a test case covering that.
 
I'm starting now to debug this issue.

**Comment by erik-vos** [comment]
Fixed.
It was a stupid oversight by me, indeed when I implemented dual trains last year.
In the case of dual trains, the `actualTrain` field has the train chosen by the player when the train was bought, the "upside" train so to say. But apparently I had forgotten to set `actualTrain` for single train cards. It's a miracle that this bug has not surfaced much earlier.

**Comment by erik-vos** [comment]
Pushed to upstream/master. It was a one-liner.
