### ISSUE TITLE
2.4.6 release for iOS (.dmg file) appears to be corrupted

### ISSUE THREAD

**Issue by cmorenoserrano** [Rails-18xx/Rails#389]
Release 2.4.5 works fine in my Mac, but 2.4.6 does not work and it tells me that it is corrupted.
Maybe double-check the release?

Many thanks in advance.

**Comment by neutronc** [comment]
Hi,
i get the same result trying to install it on my Macbook. I see no difference in the creation process however to 2.4.5. Going to rerun the build.

**Comment by neutronc** [comment]
i have triggered a new build, need to check the output.

**Comment by cmorenoserrano** [comment]
Thank you so much.

Let me also thank you personally for having developed such an amazing piece
of software. My gaming friends would not play 18xx with me unless we use
Rails.

Carlos

[image: Sonatype] <http://sonatype.com>
*Carlos Moreno Serrano*
Customer Outcomes Manager

**Comment by svoboda77** [comment]
I can confirm the bug. Version 2.4.6 says file is corrupted, version 2.4.5 works fine. Tested on a MacBook Pro (Intel CPU) running a fresh install of macOS Big Sur 11.6.1.

**Comment by neutronc** [comment]
Unless we get a developer  account with apple and sign and release the app with approval from apple we wont be able to fix this behaviour :(
