### ISSUE TITLE
1837 Player worth

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#395]
@jdgalt reported (see #394):

At start of first stock round I notice weirdness in the net worths.  Private and minor companies all seem to be valued at face (par), but coal companies are worth zero.  This seems wrong to me; I would make them all face value (100).

**Comment by erik-vos** [comment]
First, about the current valuation in Rails: I don't see the minors being valued at all. 

My fictituous player Alice has, according to Rails in a 3p v1 game at the start of OR 3.1, a worth of 835, composed from:
```
    Cash          131
    BrB           140
    KwB           170
    WB            130
    30% BK @ 63   189
    10% MS @ 75    75
                  ---
    Worth         835
```
That excludes the coal companies (as reported) but also all minors. 

But what is the real value of all these items? All rule versions are silent about that, as these understandably only talk about the total worth at game end. And I dare say that the chance that any of these non-major companies will still exist at game end is only infinitesimally different from zero.

The Sd minors come with the privates, so it's reasonable to consider their values as being included in the values of the corresponding privates, and need not be counted separately.
For the KK and Ug minors we could consider their standard buy prices as being their worth, and the coal companies are then worth 100.

As my Alice also owns EOD, EKT, MLB, S2, S4, K2, U2 and half of U3, her worth would increase by 800, for a total of 1635.

But is this all reasonable? The very same @jdgalt has in his version of the v1 rules included "A STRONG HINT" for new players, that in fact the start items should be bought at "deep discounts", so apparently their real worth is far less then their face values.
Accordingly, Lonny's v2 rules mention much lower start prices: coal companies start at 40, privates at 50-135, and KK and Ug minors at 60-80.

So if we are going to give any such companies a worth, I would rather take the v2 than the v1 face values.

And there is yet another factor. All rule versions state in the "Game End" chapter: "An exchange share in a major corporation of which the director's certificate has not been sold is worth nothing".  This is a strange statement, given the fact that coal companies may not be exchanged, not only if its major has not yet been _started_, but even if it has not yet _floated_. I'd say that no player can own an exchange share of an unstarted company. 

But I think this strange rule may become sensible if taken to imply, that all coal companies have in fact no value until their corresponding major has started, and then be valued by that major's current price. And, by extension, that all minors are in fact worth the fixed initial share value of their corresponding national companies. The latter would mean, that some of the Sd minors would be more valuable that their corresponding privates, so I would then tend to value all privates (except perhaps TR and WR) as zero.

Well, this is just a suggestion. Consider the 10% PRR share in 1830 that comes with the C&A. That share, as I understand, will only get a worth once the PRR has started and thus has a price. I think my proposal is analogous to that ancient fact.

**Comment by jdgalt** [comment]
> First, about the current valuation in Rails: I don't see the minors being valued at all.
> 
> My fictituous player Alice has, according to Rails in a 3p v1 game at the start of OR 3.1, a worth of 835, composed from:
> 
> ```
>     Cash          131
>     BrB           140
>     KwB           170
>     WB            130
>     30% BK @ 63   189
>     10% MS @ 75    75
>                   ---
>     Worth         835
> ```
> 
> That excludes the coal companies (as reported) but also all minors.

In my tests, Rails is valuing all minor companies at the value of the national company share they will trade for.  (Your "Alice" doesn't appear to have any minor companies, or I've missed something.)

> But what is the real value of all these items? All rule versions are silent about that, as these understandably only talk about the total worth at game end. And I dare say that the chance that any of these non-major companies will still exist at game end is only infinitesimally different from zero.
> 
> The Sd minors come with the privates, so it's reasonable to consider their values as being included in the values of the corresponding privates, and need not be counted separately.

As I see it the face value of the five privates that come with Sd minors include the value of the minor.  As long as the minors stay minors there is no need to apportion the cost basis between the two, but once the minors trade-in then the shares can be sold so the need does arise.  Thus I would value minors = the par value of the trade-in shares.  Which I believe is what Rails already does.

> For the KK and Ug minors we could consider their standard buy prices as being their worth, and the coal companies are then worth 100.

I only want to do this for the coal companies.

> As my Alice also owns EOD, EKT, MLB, S2, S4, K2, U2 and half of U3, her worth would increase by 800, for a total of 1635.
> 
> But is this all reasonable? The very same @jdgalt has in his version of the v1 rules included "A STRONG HINT" for new players, that in fact the start items should be bought at "deep discounts", so apparently their real worth is far less then their face values.

Yes, I do believe that.

I had to study the starting packet before I figured out that the packet is set up, on purpose, to make it almost impossible for a player to start out with two coal companies that can profitably work together.  In particular:

*  EOD and EKT both will merge into MS.  EKT doesn't even easily build to the MS home, so in practical terms EOD's owner controls how well MS will do in the game.  The start packet not only forces EKT to be bought before EOD, but makes sure that once EKT is bought, its owner does not have a chance to buy EOD unless all other players first pass it up.
*  Similarly, RGTE controls the fate of BK and thus the value of EPP, but EPP must be bought first.
*  Similarly, ZKB controls the fate of SB and thus the value of SPB, but SPB must be bought first.

> Accordingly, Lonny's v2 rules mention much lower start prices: coal companies start at 40, privates at 50-135, and KK and Ug minors at 60-80.
> 
> So if we are going to give any such companies a worth, I would rather take the v2 than the v1 face values.
> 
> And there is yet another factor. All rule versions state in the "Game End" chapter: "An exchange share in a major corporation of which the director's certificate has not been sold is worth nothing". This is a strange statement, given the fact that coal companies may not be exchanged, not only if its major has not yet been _started_, but even if it has not yet _floated_. I'd say that no player can own an exchange share of an unstarted company.

This is almost but not quite true.  The 5 train purchase forces all coal companies to exchange even if they're exchanging for shares of an unstarted major company.

> But I think this strange rule may become sensible if taken to imply, that all coal companies have in fact no value until their corresponding major has started, and then be valued by that major's current price. And, by extension, that all minors are in fact worth the fixed initial share value of their corresponding national companies. The latter would mean, that some of the Sd minors would be more valuable that their corresponding privates, so I would then tend to value all privates (except perhaps TR and WR) as zero.
> 
> Well, this is just a suggestion. Consider the 10% PRR share in 1830 that comes with the C&A. That share, as I understand, will only get a worth once the PRR has started and thus has a price. I think my proposal is analogous to that ancient fact.

That's a reasonable idea, but it runs into problems.  One is that the inferred value of a coal company would not be fixed.  It would be zero until the major company is started, but then would follow the current share price of the major company, and be affected by any event that changes that current share price.  This is not the kind of thing an accountant would put in an annual report.

**Comment by erik-vos** [comment]
> In my tests, Rails is valuing all minor companies at the value of the national company share they will trade for. (Your "Alice" doesn't appear to have any minor companies, or I've missed something.)

Yes, she has, as I added later on. But that doesn't matter. I have looked at another case, but still the same result: no worth contribution for all minors.

The default code assigns an "end of game value" (which we call "worth") only to privates (their "price" attribute) and to public company shares that have a market price (their current price). Public companies without a market price are worth zero. And the 1837-specific code does not (yet) override that in any way to give the price-less coal and minor companies a worth. The question is what we should do about that, if anything.

>> I'd say that no player can own an exchange share of an unstarted company.
> 
> This is almost but not quite true. The 5 train purchase forces all coal companies to exchange even if they're exchanging for shares of an unstarted major company.

[_red face_] Yes, I should have checked that, but forgot.

[_my proposal_]

> That's a reasonable idea, but it runs into problems. One is that the inferred value of a coal company would not be fixed. It would be zero until the major company is started, but then would follow the current share price of the major company, and be affected by any event that changes that current share price. This is not the kind of thing an accountant would put in an annual report.

I was not aware that accountancy has extended its tentacles to the 18xx realm. My proposal was based on the idea that, because all coal and minor companies are ultimately good for one share, then give them the worth of that share, once we know it, so that a merger would not cause a jump in player worth. The back side of that is, of course, that a jump will occur once a major is started.

That said, I'm not against giving the coal companies a fixed value, which I would suggest to be in the allowed major start prices range (70-104). The v1 base price of 100 fits there at the high end, so a major starting low will cause some damage. The v2 base price of 40 would be too low; the average is 70, which would just fit. We could also go for a price in the middle, e.g. 85, but that looks a bit artificial.

Did you have you any other problems with my original proposal than the accountancy argument?

**Comment by jdgalt** [comment]
No.  I'm sorry, I was just trying to lighten the mood a little.

**Comment by erik-vos** [comment]
OK, perhaps we can try to reach some agreement. Let's condense the world of possibilities into 3 options:

A. Leave it as is:
  - privates (mountain railways) worth is their v1 base price.
  - coal and minor companies worth is 0.

B. My original proposal:
  - privates worth is 0.
  - coal and minor companies worth is the current price of their related majors (once started) or nationals.

C. My modified proposal:
  - private worth is 0.
  - coal companies worth is 70.
  - minor companies worth is the current price of the related nationals.

My vote goes to A.

**Comment by jdgalt** [comment]
Of those three I like B.

**Comment by erik-vos** [comment]
Well, the response is a bit underwhelming, but nevertheless we have to come to a decision. Leaving aside the unpopular option C, on first sight the votes A:B point to a 1:1 result. But if we more appropriately look at the having-played-1837-games count, we are undoubtedly closer to 0 : ∞ . So hereby I declare option B to be the winner. Congratulations, @jdgalt ! If you have any fine tuning suggestions, please let me know a.s.a.p. 

So now I'm going to find my way through the jungle that Rails 2.0 has created: Wallets, Purses, Currencies, MoneyModels, CalculationMethods etc.  (Yes, I know that I really have to look at PublicCompany.getGameEndPrice(), which I might or might not rename to getWorth()).
