### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#4]
Currently the Rails project contains quite a lot of branches. 
I'm not sure which of these branches are still required.
But I think they should be cleaned up a little, to make it more clear, what is still in use or at least usable and what not.

**Comment by neutronc** [comment]
the main branch currently is rails_2_develop
rails_2_maintenance is the branch to fix the current Release Candidate. After a release that should be merged into rails_2_develop.
The master branch is still on 1.9.x. We'll have to decide what to do with that as one of the next steps.
other branches are either development branches from single developers you can determine them by the developers tag infront:
ev_ Erik vos
sf_ Stefan Frey
mbr_2 Martin Brumm

**Comment by madoar** [comment]
I understand the need to have the three branches:

- rails_2_develop
- rails_2_maintanance
- master (1.9.x)

Do we want to retain the other, single developer, branches?
I would suggest to move these branches to the forks of the corresponding users, because the content of these branches are normally only interesting for other people when a Pull request (PR) has been opened for them.

**Comment by neutronc** [comment]
I do agree with you, those are relicts from Sourceforge... Need to transfer that but thats a ton of work for the near future.

**Comment by blentz** [comment]
I'd say do a diff of each branch with the rails_2_develop branch. If there looks like there's some useful code in there, we can merge it or cherry-pick it, as makes sense. If there isn't anything useful, we can delete the branch.

**Comment by neutronc** [comment]
I would rather not loose my mbr_* branches Thank you

Am 10.07.17 um 21:42 schrieb Brett Lentz:

**Comment by madoar** [comment]
Are the old branches even mergeable?
As far as I understand the codebase it's quite old, so I'm not too sure if the code inside the branches doesn't differ to much from the code in the current branches `rails_2_develop` and `rails_2_maintain`

**Comment by jklap** [comment]
Do we have anything left to do on this one?

**Comment by neutronc** [comment]
no as they are archived now...
