### ISSUE TITLE
Open/closed hexes

### ISSUE THREAD

**Issue by erik-vos** [Rails-18xx/Rails#403]
I am toying with a new, very simple way to make hexes (in)accessible, as happens with Italy and Bosnia in 1837.

I have added a new stateful boolean "open" to MapHex, which by default is true. Inaccessible hexes get the value false.
The idea is that all map related effects of closed hexes can be handled via this field. 

For routing: each closed hex will not be added to the basic routing graph to begin with, so that there is no more need to remove vertices later on in a modifier. I have tested this successfully with Bosnia. Out with BzHTileModifier and ItalyTileModifier (sorry Martin)!

For map display: I have found a simple way to make a tile half transparent (by modifying the Color alpha attribute, that represents the image transparency). Doing that for the initial Bosnia tiles gives a result as below:
![DimmedBosnia](https://user-images.githubusercontent.com/13908049/116743949-f22e3f00-a9f9-11eb-9f74-f98aa0015c5d.jpg)
(any printed texts should be handled separately). 
This way we no longer need special tile images for these hexes. The backside is, that the initial Italy hexes will no longer stand out at game start; initially these look normal, and will be greyed out when Italy closes.

What do you think of this latest feature?

_Edit:_ I just realise that this will not work with a background map, unless we add some special treatment with separate pictures again. Dimming colours this way may not be my best idea after all...

**Comment by erik-vos** [comment]
In addition we could draw some line at the country borders, such as the red line around Italy that exists in the physical game. That would be a fairly simple further extension of the edge highlights we already have: impassable edges, and the bridgeable rivers in SOH. These features follow a common logic.

**Comment by neutronc** [comment]
From my PoV go ahead.

**Comment by erik-vos** [comment]
This is then how it will be at game start and after Italy has closed. Looks clear enough to me.
![1837-1](https://user-images.githubusercontent.com/13908049/116924917-c9f04b80-ac58-11eb-9c16-f4107c5fa49a.jpg)
![1837-2](https://user-images.githubusercontent.com/13908049/116924929-cceb3c00-ac58-11eb-8ad5-5a2fa8020521.jpg)
