### ISSUE TITLE
1830: Operating round without map

### ISSUE THREAD

**Issue by hipolitogomezcuello** [Rails-18xx/Rails#530]
Hello! I've been investigating and using this wonderful program on my own, and wanted to use it as a helper in my next tabletop game. In my group we really like perfect information, so having a clear networth would be really useful, but we still want to use our own map. I've found the "No map mode (for ftf play)" and it seems to be what I wanted.

However, when entering the first operating round, the software gets stuck at "Select a hex", and I've found no way of bypassing this, since it doesn't show the map and I can't select any hex I'm not sure how I would continue. I also still need to find a way to manually reduce a corporation's funds to buy trains or build on terrain without the map. Is this possible? Thanks!

**Comment by erik-vos** [comment]
I'm one of the developers, and as it seems currently the only active one, but I am not at all familiar with no-map mode, so I'm not sure if I can help you with that. I cannot exclude that some action by me unknowingly has disrupted that mode. I'll have a look anyway.

On your question to change funds: yes that is possible. Under the 'Moderator' menu there is an option 'Correction' where you can choose to change any cash amounts owned by players and companies.

**Comment by erik-vos** [comment]
I have tried to start 1830 in no-map mode, and to me it seems to work. I'm also getting the 'Select a hex' question, which is not logical, but you can safely skip it, and well as the token lay prompt. Once at the 'Buy Train' step, it is possible to enter tile and token laying costs via the 'Operating Cost' button, which apparently is added special for this mode. From the 2nd OR, you can also enter the actual revenue. This is with Rails version 2.5.0.

Why it works this way, and even if this really is the intended operational scenario, I cannot tell. But it seems to me that there is nothing in the way of using Rails in no-map mode.

**Comment by erik-vos** [comment]
Assuming, that the tile and token lay steps should be skipped in no-map mode, I have added two lines to the code in OperatingRound.nextStep() that do just that. It works for 1830. I haven't checked whether all other games use that code, although I think so. If no-one objects, this change will be in a next release.

**Comment by hipolitogomezcuello** [comment]
Thank you @erik-vos ! That info was very useful, I'll be using Rails for my game friday. For some reason I was using the pbem profile, so I wasn't seeing the "skip" button on the hex laying phase. I also didn't know about the Correction mode.

Thank you again! Awesome software
