### ISSUE TITLE
License change request

### ISSUE THREAD

**Issue by JimWuerch** [Rails-18xx/Rails#57]
See [here](https://github.com/JimWuerch/HexxTrains) for my repo, with a README describing .Net Standard.

I would like to explore the possibility of changing the license of Rails from GPL to MIT.  There's a small list of contributors, and hopefully the few people that have contributed the majority of the work would like to see Rails run on modern and mobile platforms (such as an iPad).  

I'm requesting this because I've created a .Net Standard implementation of the rails engine (non-GUI parts) in C# as a library that can be used in all popular OSs, including iOS, Android, Linux, etc.  

I'd love to see more people playing 18xx, but the barrier to entry is very high.  Having an app that runs on an iPad or that is on Steam would greatly increase the appeal.

Modern development relies on a lot of different technologies, and it's very difficult to navigate the minefield that is GPL. For multiplayer, I'd really like to use 3rd party interfaces, but those are not going to be GPL compatible.  Additionally, I'd have to segregate all the code that I write from scratch from the ported code, as I'd rather not have to be restricted where I can re-use my own code in the future.

Using the library I've created, it's possible to create a game with Unity3d or Xamarin Forms to create a cross-platform application.  

While I only have the readme available on github, I'll post the whole library, the unit tests and a test application that goes through the opening round as examples.  The example application has no GUI, and will run on all the .Net Standard supported platforms.  I've currently only ported the base 1830 game, sans UI.

**Comment by blentz** [comment]
I see no reason to relicense. There is zero benefit to Rails or its authors.

It makes no sense to me that we would let you take this codebase for your own purposes without contributing anything back to the codebase. 

The GPL exists to prevent exactly this kind of one-sided arrangement.  If the code is good enough that you want to use it, then it's good enough for you to compensate us by giving us what we gave you - code.

**Comment by JimWuerch** [comment]
I apologize if it sounded like I was trying to 'take the code for my own purposes'.  I should've cleaned up things and posted to github first.

The ported source code is now available here:  https://github.com/JimWuerch/GameLib18xx

The reason I'd like to change things is because it's impossible to distribute the source code for things like Unity3d.  The Rails code will stay isolated to comply with your request.

**Comment by JimWuerch** [comment]
In 2005, Java was a good selection for cross-platform development.  In 2018 it's not, dalvik notwithstanding.   .Net Standard is a standards-based cross platform API specification that is implemented in a number of cross platform tools, such as .net core, mono and unity.  

No .Net Standard platform is a second class citizen.  It's a mistake to think that Windows is the primary target for .Net Standard.  .Net Standard was born of the .Net Core effort, which is an open source reimplementation of the .net libraries, using the open source Rosilyn compiler to run .net apps on linux servers.   I'd suggest actually reading about .Net Core before trashing its cross-platform chops.   .Net Core and .Net Standard are a far safer bet than whatever Oracle is doing to java these days.  

Using Xamarin, I can write a single codebase and deploy it across Windows, Android and iOS.  There is ample support for multiplayer services for C# applications, and I hope to have something soon demonstrating the opening round as a multiplayer app with an iPad playing against a Windows PC, playing against an Android phone.

Unity3d allows creating an app and running it on windows, android, macos, linux, ios, xbox, etc.   Many, many, many games are written in Unity, and Unity was originally a Mac application.  Since Unity is based on mono (itself originally a linux port of .net), it can use a .net standard library directly.

I understand that you've put more than a decade of work into this, and it seems you have more than a little dislike of C# because it was developed by Microsoft.  That's understandable, given the state of the world 20 years ago, but along came mobile and the world is a far different place today.

I again apologize for my introduction.   I'm not a java programmer, and I what I can offer to the existing project community is a port to .Net Standard.   I'm betting that there's lots more C# programmers who'd like to try something in Unity, than there are desktop java programmers looking to write something in swing.  Heck, you should take a look at it, you might think it's kind of cool.

**Comment by blentz** [comment]
Your discussion about C# is a straw man - it says a lot about your experiences working in C# and nothing about my actual opinions of the language. You'd be getting this same response if you were suggesting a port to *any* language that isn't Java.

Again, your focus is in the wrong place and, because of that, your message misses the mark. 

Let me spell it out for you.

You've literally not submitted a single line of code to the project. Why exactly should we care about what you think?

Open source communities are meritocracies. People who contribute code get to have an opinion. People who don't contribute code don't get a vote.

So, either raise a PR and contribute to the project or move on. There's no further discussion to be had if you're not willing to join the project.

**Comment by JimWuerch** [comment]
PR created.  Deleted my repos.
