### ISSUE TITLE
JGraph

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#62]
While working on #61 I've tried to update the used dependencies.
During this, I've seen quite old dependencies, which are out of date for quite a lot of years.
One such dependency is `jgraph`, which was last updated on Nov 23, 2009, i.e. ~9 years ago.
Meanwhile JGraph has been renamed to JGraphX (see https://github.com/jgraph/jgraphx).
During the name change, quite a lot of files have been renamed and overhauled.

I would like to update JGraph to JGraphX, but because of the changes this is a lot of work.
Additionally I'm not sure where we use JGraph currently.
As far as I know the library is a graph visualization library, but I don't know where we use such a library in our GUI.
Can someone tell me, for what we use the JGraph library?

**Comment by blentz** [comment]
I'm supportive of the change. Let's get this updated.

IIRC, JGraph was being used to produce net worth graphs to show player scores over the course of the game.
