### ISSUE TITLE
18EU hex reservation doesn't cater for closed minors

### ISSUE THREAD

**Issue by DestrinStorm** [Rails-18xx/Rails#72]
The hexes reserved for minor company tile placement in 18EU doesn't cater for the situation where the minors are closed.  Anything that is reserved = (numeric) (F9, K2, S6, H3) cannot be placed/upgraded unless you are doing it with that minor, once the minor has been formed into a major, this prevents any hex placement in that location

**Comment by neutronc** [comment]
Fixed in Code base new release upcoming
