### ISSUE TITLE
1830 - problem when no shares to sell at all in forced buy

### ISSUE THREAD

**Issue by peter-de-boer** [Rails-18xx/Rails#73]
Following situation: a player must force-buy a train but does not have enough money, so he should sell shares. But when he has no shares to sell at all (due to pool limits etc.), Rails basically does not handle this correctly, the game basically stalls. 
[1830_20190306_1455_weisswurst.zip](https://github.com/Rails-18xx/Rails/files/2936941/1830_20190306_1455_weisswurst.zip)

**Comment by neutronc** [comment]
fix developed will be in next beta release deployed.
