### ISSUE TITLE
1835 - wrong player gets PD if the last action was a sell action

### ISSUE THREAD

**Issue by peter-de-boer** [Rails-18xx/Rails#76]
According to the rules, the player left to the player who did the last buy action gets the PD.

In the implementation, if the last action was a sell action though, the player left to the seller gets the PD. 

See the attached example. Peter did the last action (sell), and Pep got the PD. But according to the rules, Hakko (left to Dan who was the last buyer) should get PD.
[1835_20191026_1505_Dan.zip](https://github.com/Rails-18xx/Rails/files/3774956/1835_20191026_1505_Dan.zip)

**Comment by erik-vos** [comment]
No. The original AH rulebook states in rule 4.0: "When everyone has 
stopped trading the player on the left of the last player to buy or sell 
is given the Priority Card (...)".
You are referring to rule 7.0, which deals with the first stock round 
only, in which it is not allowed to sell any stock.

Erik

Op 26-10-2019 om 17:11 schreef peter-de-boer:

**Comment by peter-de-boer** [comment]
No, I am referring to the original German rules (Hans im Glück, 1990). 
Rule 2.3 says:

"Der Spieler links von
demjenigen Spieler, der zuletzt eine Kaufaktion getätigt hat. bekommt die
Holzlokomotive (ist Startspieler der nächsten AR)."

**Comment by erik-vos** [comment]
Sorry, please disregard my previous message, in which I was referring to 
1830. Indeed 1835 seems to differ, a deviation from 1830 that has 
escaped my attention so far. That also is the cause that Rails has not 
implemented it. The 18xx rules difference list indeed reports this 
difference for 1835 and a few other games.

My bad.
Erik


Op 26-10-2019 om 17:11 schreef peter-de-boer:

**Comment by neutronc** [comment]
closed with latest commit to Repository.
