### ISSUE TITLE
1835 - director may not exchange 20% for 10% share when selling

### ISSUE THREAD

**Issue by peter-de-boer** [Rails-18xx/Rails#77]
This is another difference between 1835 and many other titles.

See the attached game. In that game, Dan is president with just a 20% director certificate. Rails allows him to sell 10%, transferring the presidency to Peter. This is not allowed according to the rules.

In many 18xx titles this is allowed, and often there is a section in the rules that deals with this situation, e.g. by describing a procedure like: the old president announces the sell, he exchanges his president share by two single shares with the new president, and then executes the sell (which then indeed maybe the sell of a single share).

In 1835, this is forbidden. There is no rule describing this procedure of exchanging shares. Instead, rule 2.6.3.2 (Hans im Glück 1990) says: 

`Jedes „Papier" kann nur als Ganzes verkauft werden, nicht teilweise (z.B. durch den Austausch einer 20%-Aktie durch einen 10%-Anteil).`

This holds for all 20% shares, there is no exception for 20% president shares.

Moreover, the situation in the attached game, with 40% of the shares in pool, is even explicitly forbidden in the rules. Rule 3.3.7:

`Befinden sich bereits 40% seiner AG im Bank-Pool, kann der Direktor also eine 20%-Direktor-Aktie nicht direkt verkaufen.`

What is allowed though (explicitly by 3.3.7), is that a director first buys a 10% share (if allowed by certificate limits of course) and then sells his 20% share. This needs a buy action though. In the current Rails implementation, the director can sell 10% and then still do a buy action.

By the way, is there actually anybody working on issues? The last release (Rails 2.0 Release Candidate 3) is already more than two years ago.

**Comment by peter-de-boer** [comment]
And here is the attachment ;)
[1835_20191209_1813_Dan.zip](https://github.com/Rails-18xx/Rails/files/3943676/1835_20191209_1813_Dan.zip)

**Comment by neutronc** [comment]
Hi Peter,
please check the following file.
[rails-2.0.RC5.8.zip](https://github.com/Rails-18xx/Rails/files/4021020/rails-2.0.RC5.8.zip)

And use this save game :)
[1835_20200103_2142_Dan.zip](https://github.com/Rails-18xx/Rails/files/4021021/1835_20200103_2142_Dan.zip)
Regards
Martin

**Comment by peter-de-boer** [comment]
Hi Martin,

Thanks a lot for fixing this!
Unfortunately, it is not completely bug-free yet.
What is working correctly now is that the director is not able to sell his 20% share if there is 40% in the pool. Thanks for that!
But if there is just 30% in the pool, then the director should be able to sell his 20% share. But in the new version also in that situation the director cannot sell his 20% share. See the attached game.

Regards,
Peter
[1835_20200107_0738_Dan.zip](https://github.com/Rails-18xx/Rails/files/4029409/1835_20200107_0738_Dan.zip)

**Comment by neutronc** [comment]
Hi Peter,

please check the following and the attached save game.

I am not saying i didnt break anything though :)
[1835_20200301_1656_Dan.zip](https://github.com/Rails-18xx/Rails/files/4272117/1835_20200301_1656_Dan.zip)
[rails-2.0.RC5.9.zip](https://github.com/Rails-18xx/Rails/files/4272132/rails-2.0.RC5.9.zip)

Regards
Martin

**Comment by neutronc** [comment]
And yes i broke something...

Need to correct this, comning back to you later, sorry.
Martin
