### ISSUE TITLE
Repo and build doco out of date

### ISSUE THREAD

**Issue by jklap** [Rails-18xx/Rails#80]
Noticed the 2.1beta1 was dropped but doesn't look like the repo has been updated? I've got some changes I've been playing with and would like to merge them and build my own testing jar-- could someone please update?

Second, I noticed both gradle and maven builds-- which is maintained?

Finally, which branch should be used?

Thanks!

**Comment by neutronc** [comment]
Morning @jklap 
the release wsa done out of the rails_2_maintenance branch. Thats the logical branch for the early 2.0 state release that was leaning close to 1.{8,9}.

New development should be based of rails_2_develop.

I'll be transferring my fixes from the latest release to rails_2_develop today.

Some day we will really need to clean out the mess with the branches :)
Regards
Martin
