### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jklap** [Rails-18xx/Rails#85]
Git: 
`jklap$ git fetch && git status
On branch rails_2_maintenance
Your branch is up to date with 'origin/rails_2_maintenance'.`

Build:

`jklap$ gradle assemble
Configure project :
launch4j.description property is deprecated. Use launch4j.fileDescription instead.

Task :compileJava FAILED
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:530: error: 'else' without 'if'
        else {
        ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:535: error: illegal start of type
    } else {
      ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:535: error: ';' expected
    } else {
          ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:537: error: illegal start of type
        super.finishRound();
        ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:537: error: <identifier> expected
        super.finishRound();
             ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:537: error: ';' expected
        super.finishRound();
              ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:537: error: illegal start of type
        super.finishRound();
                         ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:537: error: <identifier> expected
        super.finishRound();
                          ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:541: error: class, interface, or enum expected
    private boolean findStartingPlayerForCoalExchange(PublicCompany company) {
            ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:543: error: class, interface, or enum expected
        List<PublicCompany> minors = new ArrayList<PublicCompany>();
        ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:544: error: class, interface, or enum expected
        String type;
        ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:546: error: class, interface, or enum expected
        for (PublicCompany comp : comps) {
        ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:548: error: class, interface, or enum expected
            if (type.equals("Coal")) {
            ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:550: error: class, interface, or enum expected
                if (comp.getRelatedNationalCompany().equals(company.getId())) {
                ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:553: error: class, interface, or enum expected
                    if (((GameManager_1837) gameManager).getPlayerToStartCERound()== null) {
                    ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:555: error: class, interface, or enum expected
                        return true;
                        ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:557: error: class, interface, or enum expected
                    }
                    ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:566: error: class, interface, or enum expected
                return true;
                ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:567: error: class, interface, or enum expected
            }
            ^
/Users/jklap/Rails/src/main/java/net/sf/rails/game/specific/_1837/OperatingRound_1837.java:570: error: class, interface, or enum expected
    }
    ^
20 errors

FAILURE: Build failed with an exception.`

**Comment by neutronc** [comment]
My bad :( didnt update the file in question give me a minute.

**Comment by neutronc** [comment]
Should compile now
