### ISSUE TITLE
Failed reload during 1830 auction B&O par setting

### ISSUE THREAD

**Issue by jklap** [Rails-18xx/Rails#90]
[1830_20200316_2345_Josh.rails.zip](https://github.com/Rails-18xx/Rails/files/4341346/1830_20200316_2345_Josh.rails.zip)

Attached is a saved file created with the 2.1beta.

We had just completed the auction of an 1830 game and I had just set the B&O par (Jason) and passed the file to Josh to first SR action. This was created using Autoload/Save with 3 players.

It fails to load. In poking around it seems that the failure is logging happening here:

GameManager.java:899:
```        
        // New in Rails2.0: Check if the action is allowed
        if (!possibleActions.validate(action)) {
            DisplayBuffer.add(this, LocalText.getText("ActionNotAllowed",
                    action.toString()));
            return false;
        }
```

Note, if I comment out the `return false;` the file will load and seems to play fine.

For reference, here is what I see in the log files:

```2020-03-16 20:09:22 DEBUG Turn: Jason
2020-03-16 20:09:22 DEBUG Action (Jason): Jason executed BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 225,
 selected = false, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O, associatedSharePrice = 67
2020-03-16 20:09:22 DEBUG Jason may: Jason may BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 220, selected
= true, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O
```

It looks like it's failing due to the price of 225 vs 220. Note that this was a single bid on B&O so should have been 225 (and was displayed as 225 in the UI).

I'm guessing is has to do with logic in StartRound_1830.setPossibleActions():94:

```                } else if (item == startPacket.getFirstUnsoldItem()) {
                    if (item.getBidders() == 1) {
                        // Bid upon by one player.
                        // If we need a share price, ask for it.
                        PublicCompany comp = item.needsPriceSetting();
                        if (comp != null) {
                            playerManager.setCurrentPlayer(item.getBidder());
                            item.setStatus(StartItem.NEEDS_SHARE_PRICE);
                            BuyStartItem newItem =
                                    new BuyStartItem(item, item.getBasePrice(),
                                            true, true);
```

Looks to me as the `item.getBasePrice()` should actually be `item.getBid()`?

Further log details for reference:

```2020-03-16 20:09:22 DEBUG Jason may: Jason may NullAction, mode = PASS, optionalLabel = NULL
2020-03-16 20:09:22 DEBUG Jason may: Jason may CorrectionModeAction, correctionType = CORRECT_CASH, active = false
2020-03-16 20:09:22 DEBUG Jason may: Jason may CorrectionModeAction, correctionType = CORRECT_MAP, active = false
2020-03-16 20:09:22 DEBUG ChangeSet: Add Change for BooleanState{uri=/reportManager/displayBuffer/autoDisplay}: From false to true
2020-03-16 20:09:22 DEBUG ChangeSet: Add Change for ArrayListState{uri=/reportManager/displayBuffer/buffer}: Add Action Jason executed BuyStartItem, start
Item = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 225, selected = false, setSharePriceOnly = true, sharePriceToSet = true, company
NeedingSharePrice = B&O, associatedSharePrice = 67 is not allowed at index 0
2020-03-16 20:09:22 DEBUG To display: Action Jason executed BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 2
25, selected = false, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O, associatedSharePrice = 67 is not allowed
2020-03-16 20:09:22 WARN  Replay of game interrupted
2020-03-16 20:09:22 ERROR Game load failed
net.sf.rails.util.RailsReplayException: [LoadInterrupted]
        at net.sf.rails.util.GameLoader.replayGame(GameLoader.java:271) ~[rails-2.1beta1-all.jar:na]
        at net.sf.rails.util.GameLoader.createFromFile(GameLoader.java:330) ~[rails-2.1beta1-all.jar:na]
        at net.sf.rails.util.GameLoader.loadAndStartGame(GameLoader.java:60) ~[rails-2.1beta1-all.jar:na]
        at net.sf.rails.ui.swing.GameSetupController.loadAndStartGame(GameSetupController.java:142) [rails-2.1beta1-all.jar:na]
        at net.sf.rails.ui.swing.GameSetupController.access$1700(GameSetupController.java:53) [rails-2.1beta1-all.jar:na]
        at net.sf.rails.ui.swing.GameSetupController$LoadAction$1.run(GameSetupController.java:216) [rails-2.1beta1-all.jar:na]

**Comment by jklap** [comment]
Actually looks like there is an additional issue as `selected` is different between the two BuyStartItems also. Suspect this is due to the file passing maybe? The previous item was contested between the other two players.

**Comment by jklap** [comment]
Final note-- when I attempted to recreate it manually (by myself, no autoload/save, me acting as all three players) this is what I ended up with in the log:

```2020-03-16 23:28:04 DEBUG Action (Jason): Jason executed BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 220,
 selected = true, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O, associatedSharePrice = 67
2020-03-16 23:28:04 DEBUG Jason may: Jason may BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 225, selected
= true, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O
```

Note that I *did* bid 225 for B&O even though the above says 220, from earlier in the log:
```2020-03-16 23:28:04 DEBUG Processing action Jason executed BidStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, minimumBid = 225, bidIncrement = 1, selected = false, selectForAuction = false, actualBid = 225
```

The `selected` flag is also `true` but I suspect that is also likely due to not having autoload/save enabled?

**Comment by neutronc** [comment]
Selected should be true if you bought an item directly iirc.

**Comment by neutronc** [comment]
One important information though
2.1 is from the rails_2_maintenance branch not rails_2_develop that should have a 2.2alpha version.

**Comment by jklap** [comment]
Yes, have been looking at/using the rails_2_maintenance branch.

Should we be testing/using a build from rails_2_develop? Is it stable enough for playing with people that don't care too much to test? Is there are missing functionality?

**Comment by neutronc** [comment]
i guess your first point with item.getBid() was spot on...

**Comment by neutronc** [comment]
Interesting that the lines you list are differing from what i see. Investigating further.

**Comment by neutronc** [comment]
Now thats a strange thing to happen here:
the action being checked is:
Jason executed BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 225, selected = false, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O, associatedSharePrice = 67
The possible action however is:
Jason may BuyStartItem, startItem = StartItem{URI=/CompanyManager/Initial/B&O}, itemIndex = 5, price = 225, selected = true, setSharePriceOnly = true, sharePriceToSet = true, companyNeedingSharePrice = B&O

so the equal check fails on the reloaded object... now hows that possible...

**Comment by neutronc** [comment]
found it:

` else if (item.getStatus() == StartItem.NEEDS_SHARE_PRICE) {
                    /* This status is set in buy() if a share price is missing */
                    playerManager.setCurrentPlayer(item.getBidder());
                    possibleActions.add(new BuyStartItem(item, item.getBid(), **false**, true));
                    passAllowed = false;
                    break; // No more actions
                } else if (item == startPacket.getFirstUnsoldItem()) {
                    if (item.getBidders() == 1) {
                        // Bid upon by one player.
                        // If we need a share price, ask for it.
                        PublicCompany comp = item.needsPriceSetting();
                        if (comp != null) {
                            playerManager.setCurrentPlayer(item.getBidder());
                            item.setStatus(StartItem.NEEDS_SHARE_PRICE);
                            BuyStartItem newItem =
                                    new BuyStartItem(item, item.**getBid()**,
                                            **false**, true);
                            possibleActions.add(newItem);`

Two mistakes (i think) in one call if i set the selected attribute stemming from the real action to false in the replayed action and change the item.getBasePrice to item.getBid()

it loads..

**Comment by neutronc** [comment]
Now running the tests...

**Comment by neutronc** [comment]
Thanks for finding that bug 👍

**Comment by jklap** [comment]
The code presented was from the rails_2_maintenance branch.

I don't think the `selected` code change from `true` to `false` is going to fix the issue. It fixes the load of THIS game but I believe the flag should actually be set to 'true` (as it was) as non-autoload/save games are going to see it as `true`. The autoload/save games are getting that set to `false` in the lines above (ie around line 88) and *that* is what I think needs to be changed from `false` to `true`. 

Either way, the saved game has incorrect saved data so there is no change we can/should make in code to address it and fix loading of this game.

Also did you see my question above?

> Yes, have been looking at/using the rails_2_maintenance branch.

> Should we be testing/using a build from rails_2_develop? Is it stable enough for playing with people that don't care too much to test? Is there are missing functionality?

**Comment by neutronc** [comment]
Hi Jklap,
i checked the behaviour of the game against test games with the fix. They loaded ok,

The problem here is that the actual action was a different one than the action the game thought should be done.

You can test the game load it with a new build from the committed version right now. Restart the game and play it  (without bidding on the B&O). And if that comes up ok then we are safe.

**Comment by neutronc** [comment]
btw in the net.sf.rails.utils package theres a file called listAndFixSaveFiles.
There you can see the actions saved in a save file..
Regards,
Martin

**Comment by neutronc** [comment]
Please find enclosed two zip files with different startround actions
[1830-Startround-saves.zip](https://github.com/Rails-18xx/Rails/files/4353575/1830-Startround-saves.zip)

They work sofar :)

Btw if you look nuder documentation, you can find a slack channel there if you are so inclined :)

**Comment by jklap** [comment]
Hi, yep, understand why it wasn't loading. Tested both scenarios with autoload/save -- ie B&O bidder is active player and B&O bidder is not active player and both are fine-- both saved files have false as that flag.
